# docker-compose.yml
services:
  postman-viewer:
    #platform: ${POSTMAN_PLATFORM:-linux/amd64}
    #build:
    #  context: .
    #  dockerfile: ${POSTMAN_DOCKERFILE:-Dockerfile.amd64}  # use Dockerfile.arm64 para hosts ARM
    image: caiocf/postman-viewer:9.31.30_amd64
    container_name: postman-viewer
    restart: unless-stopped
    environment:
      - RESOLUTION=1920x1080x24
      - NOVNC_PORT=8080
    ports:
      - "8080:8080"
    #volumes:
    #  - type: bind
    #    source: "$HOME/Library/Application Support/Postman/Partitions"
    #    target: /home/app/.config/Postman/Partitions
    #    read_only: true  # descomente se quiser evitar alteracoes no host
      
    # windows: substitua a origem por '${APPDATA}\\Postman\\Partitions'
    # macOS: substitua a origem por '$HOME/Library/Application Support/Postman/Partitions'
    # Linux: substitua por '$HOME/.config/Postman/Partitions'
